version: '3.1'

services:
  diapets-pg:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: diapets_api_development
    volumes:
      - diapets-pg-data:/var/lib/postgresql/data
volumes:
    diapets-pg-data: