class ErrorCodes
  CODES = {
    :NOT_FOUND => "NOT_FOUND",
    :INTERNAL_SERVER_ERROR => "INTERNAL_SERVER_ERROR",
    :INVALID_CREDENTIALS => "INVALID_CREDENTIALS",
    :INVALID_TOKEN => "INVALID_TOKEN",
    :UNAUTHORIZED => "UNAUTHORIZED",
  }
end